### ISSUE TITLE
Haxe 4.3.1

### ISSUE THREAD

**Issue by datee** [gepatto/pisetup#1]
Hi! Is it possible to get binaries for 4.3.1 working? 🙂

**Comment by gepatto** [comment]
Just the haxe 4.3.1 binaries?  No problem, working with them right now.
Use my setupscript:
https://gist.github.com/gepatto/e0da23b7392de6e96b71b525bfd96575
Or I can send the binaries.

**Comment by gepatto** [comment]
Just update this repository with the archived binaries and the new InstallScript :
CompleteHaxeLimeInstall_Menu_RPi.sh

**Comment by datee** [comment]
wow, fantastic - that was fast! 👍 Thanks alot! 🥇
